name: Echo Secret

on:
  workflow_call:
    inputs:
      secret-name:
        type: string
        description: 'シークレット名'
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: set env
        run: |
          echo "SECRET_NAME=${{ inputs.secret-name }}" >> $GITHUB_ENV
      - name: Echo secrets
        run: |
          echo "secret name: ${{ inputs.secret-name }}"
          echo "secret name: ${{ inputs['secret-name'] }}"
          echo "SECRET_NAME=${{ env.SECRET_NAME}}"
          echo ${{ format('{0}', inputs.secret-name) }}
          echo ${{ format('{0}', env.SECRET_NAME) }}
          echo "received secret key: ${{ secrets['DUMMY_SECRET_KEY'] }}"
          echo "received secret key: ${{ secrets[format('{0}', env.SECRET_NAME)] }}"
