name: Echo Secret

on:
  workflow_call:
    inputs:
      secret-name:
        type: string
        description: 'シークレット名'
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        run: |
          echo "secret name: ${{ inputs.secret-name }}"
          echo "secret name: ${{ inputs['secret-name'] }}"
          echo "SECRET_NAME=${{ inputs.secret-name }}" >> $GITHUB_ENV
          echo "SECRET_NAME=$SECRET_NAME"
          echo "received secret key: ${{ secrets[SECRET_NAME] }}"
